MontalvoTensionController/ProcessLogger/config/routes.rb
ProcessLogger::Application.routes.draw do

  resources :messages do
    collection do
      get 'chart'
      get 'chart_data'
      get 'tension_graph'
    end
  end

  root 'welcome#index'

end

MontalvoTensionController/ProcessLogger/app/models/message.rb
require 'twilio-ruby'

class Message < ActiveRecord::Base
  validates :process, :presence => true
  validates :sender, :presence => true

  before_save do
    x = JSON.parse(self.text)
    self.adc1 = x['ADC1']
  end


end

MontalvoTensionController/ProcessLogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

MontalvoTensionController/ProcessLogger/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_filter  :verify_authenticity_token

  def index
    @message = Message.all
  end

  def chart
  end

  def tension_graph
  end

  def chart_data
    @message = Message.last
    render json: [@message.id, @message.adc1]
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
  end

  def create
    # render plain: params[:message].inspect
    @message = Message.new(message_params)

    @message.save
    redirect_to(@message)
    send_alarms(@message)
  end




  protected


    def send_alarms(message)
      require 'twilio-ruby'



      if @message.adc1 > 0.8
        # put your own credentials here
        account_sid = 'ACcf3d9b19452bf652b424aec7f1e4c0d5'
        auth_token = 'a44f7f75644477c22b4d7be9169bf88d'

        # set up a client to talk to the Twilio REST API
        @client = Twilio::REST::Client.new account_sid, auth_token

        @client.account.messages.create({
                                            :from => '+14697895468',
                                            :to => '2145174227',
                                            :body => 'the value of Tension is now:'<<@message.adc1.to_s,
                                        })
      elsif @message.adc1 > 0.65
        TensionMailer.sample_email(@message).deliver

      end
    end

    def send_sms(account_sid, auth_token, from, to, body)

    end

    def send_voice_message

    end

  private
    def message_params
      #params.require(:message).permit(:process, :sender, :text)
      params.permit(:process, :sender, :text, :adc1, :adc2, :adc3, :adc4, :adc5, :adc6, :adc7, :adc8)
    end

end

MontalvoTensionController/ProcessLogger/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

MontalvoTensionController/ProcessLogger/app/helpers/application_helper.rb
module ApplicationHelper
end

MontalvoTensionController/ProcessLogger/app/helpers/messages_helper.rb
module MessagesHelper
end

MontalvoTensionController/ProcessLogger/app/helpers/welcome_helper.rb
module WelcomeHelper
end

MontalvoTensionController/ProcessLogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProcessLogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

MontalvoTensionController/ProcessLogger/app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MontalvoTensionController/ProcessLogger/app/views/messages/_message.html.erb
<p>
  <strong>Process:</strong>  <%= message.process %>
  <strong>, Sender:</strong>  <%= message.sender %>
  <strong>, Text:</strong>  <%= message.text %>
</p>

MontalvoTensionController/ProcessLogger/app/views/messages/chart.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>

<div id="container" style="width:100%; height:400px;"></div>

<script>

    var chart; // global

    var valueTemp = 10;

    /**
     * Request data from the server, add it to the graph and set a timeout
     * to request again
     */
    function requestData() {
        $.ajax({
            url: 'http://0.0.0.0:3000/messages/chart_data',
            success: function(point) {
                var series = chart.series[0],
                        shift = series.data.length > 20; // shift if the series is
                                                         // longer than 20

                //increment
                valueTemp +=1;

                // add the point
                // chart.series[0].addPoint(point, true, shift);
                chart.series[0].addPoint(valueTemp, true, shift);

                // call it again after one second
                setTimeout(requestData, 1000);
            },
            cache: false
        });
    }


    $(document).ready(function() {
        chart = new Highcharts.Chart({
            chart: {
                renderTo: 'container',
                defaultSeriesType: 'spline',
                events: {
                    load: requestData
                }
            },
            title: {
                text: 'Live Tension data'
            },
            xAxis: {
                type: 'datetime',
                tickPixelInterval: 150,
                maxZoom: 20 * 1000
            },
            yAxis: {
                minPadding: 0.2,
                maxPadding: 0.2,
                title: {
                    text: 'Value',
                    margin: 80
                }
            },
            series: [{
                name: 'Tension',
                data: []
            }]
        });
    });

</script>

MontalvoTensionController/ProcessLogger/app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

MontalvoTensionController/ProcessLogger/app/views/messages/index.html.erb
<h1>Messages</h1>
<%= render partial: "message", collection: @message %>

<%= link_to 'New message', new_message_path %>

MontalvoTensionController/ProcessLogger/app/views/messages/new.html.erb
<h1>New Log Message</h1>

<%= form_for :message, url: messages_path do |f| %>
    <p>
      <%= f.label :process %><br>
      <%= f.text_field :process %>
    </p>

    <p>
      <%= f.label :sender %><br>
      <%= f.text_field :sender %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', messages_path %>

MontalvoTensionController/ProcessLogger/app/views/messages/show.html.erb
<p>
  <strong>Process:</strong>
  <%= @message.process %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender %>
</p>

<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>

<%= link_to 'Back', messages_path %>

MontalvoTensionController/ProcessLogger/app/views/messages/tension_graph.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="content-type" content="text/html;charset=utf-8">
  <title>d3.js gauges</title>

  <style>

      body
      {
          font: 10px arial;
      }

  </style>

  <script type="text/javascript" src="http://mbostock.github.com/d3/d3.js"></script>
  <script type="text/javascript" src="gauge.js"></script>

  <script>


      var gauges = [];

      function createGauge(name, label, min, max)
      {
          var config =
          {
              size: 120,
              label: label,
              min: undefined != min ? min : 0,
              max: undefined != max ? max : 100,
              minorTicks: 5
          }

          var range = config.max - config.min;
          config.yellowZones = [{ from: config.min + range*0.75, to: config.min + range*0.9 }];
          config.redZones = [{ from: config.min + range*0.9, to: config.max }];

          gauges[name] = new Gauge(name + "GaugeContainer", config);
          gauges[name].render();
      }

      function createGauges()
      {
          createGauge("tension", "Tension");
          createGauge("angle", "Angle");
          createGauge("ADC1", "Volt Percent");
          //createGauge("test", "Test", -50, 50 );
      }

      function updateGauges()
      {
          /*
          var message = Message.last;

          var valueADC1 = message.adc1;

          gauges["ADC1"].redraw(valueADC1)
*/

          for (var key in gauges)
          {
              var value = getRandomValue(gauges[key])
              gauges[key].redraw(value);
          }

      }

      function getRandomValue(gauge)
      {
          var overflow = 0; //10;
          return gauge.config.min - overflow + (gauge.config.max - gauge.config.min + overflow*2) *  Math.random();
      }

      function initialize()
      {
          createGauges();
          setInterval(updateGauges, 5000);
      }

  </script>


</head>

<body onload="initialize()">
<span id="memoryGaugeContainer"></span>
<span id="cpuGaugeContainer"></span>
<span id="networkGaugeContainer"></span>
<span id="testGaugeContainer"></span>
</body>

</html>

MontalvoTensionController/ProcessLogger/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<h1>Hello, Rails!</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to 'My Blog', controller: 'messages' %>